"""Testing module for api train. This is a test file designed to use
pytest and prepared for some basic assertions and to add your own tests.

You can add new tests following the next structure:
```py
def test_{description for the test}(training):
    assert {statement with metadata that returns true or false}
```

The module conftest.py includes the fixture to return to your tests the value
generated by your function defined at `api.train` inside the test variable
`training`.
"""
# pylint: disable=redefined-outer-name
# pylint: disable=unused-argument


def test_something(training):
    """This is a test template to complete with some assertions."""
    # assert training.something == some_value
    raise NotImplementedError  # TODO: Delete after adding asserts
